In [1]:
#7-14 分别使用zeros、full、eye、random函数创建2行2列的数组
import numpy as np
a = np.zeros((2,2))
print(a)
b = np.zeros((1,2))
print(b)
c = np.full((2,2),7)
print(c)
d = np.eye(2)
print(d)
e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[0. 0.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.97363339 0.11432799]
 [0.43827325 0.58347221]]


In [2]:
#7-15 创建一个3*4的数组，并输出和更新数组中的元素
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a
b = a[:2,1:3]
b
print(a[0,1])
b[0,0] = 77
print(a[0,1])
row_r1 = a[1,:]
row_r2 = a[1:2,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

2
77
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


In [4]:
# 7-16 创建3*2的数组，并输出其中的元素
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))
print(a[[0,0],[1,1]])
print(np.array(a[0,1],a[0,1]))

[1 4 5]
[1 4 5]
[2 2]
2


In [8]:
# 7-17 创建一个4*3的数组a和一个1*4的数组b，利用数组b读取数组a的元素
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b = np.array([0,2,0,1])
print(a[np.arange(4),b])
a[np.arange(4),b]+=10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [10]:
# 7-18 创建一个3*2的数组，并输出大一2的元素
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a)
bool_idx = (a>2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])
x = np.array([1,2])
print(x.dtype)
y = np.array([1.0,2.0])
print(y.dtype)
x = np.array([1,2],dtype=np.int64)
print(x.dtype)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
int32
float64
int64


In [13]:
# 7-19 创建一个2*2的数组，实现并输出数组的加减乘除开方运算结果
import numpy as np
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(np.sqrt(x))
x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))
print(x.T)

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1 2]
 [3 4]]
10
[4 6]
[3 7]
[[1 3]
 [2 4]]


In [14]:
# 7-20 创建一个series，并更新series索引
import pandas as pd
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)
s = pd.Series(data,index=[100,101,102,103])
print(s)

0    a
1    b
2    c
3    d
dtype: object
100    a
101    b
102    c
103    d
dtype: object


In [15]:
#7-21 使用字典再创建一个series。并更新series索引
import pandas as pd
data = {'a':0,'b':1,'c':2}
s = pd.Series(data)
print(s)
s = pd.Series(data,index=['b','c','d','a'])
print(s)

a    0
b    1
c    2
dtype: int64
b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64


In [16]:
#7-22 使用常数创建一个series
s = pd.Series(5,index=[0,1,2,3])
print(s)

0    5
1    5
2    5
3    5
dtype: int64


In [21]:
# 7-23 创建一个series，并要求读取series中的元素
s = pd.Series(range(5),index=['a','b','c','d','e'])
print(s)
s[1]
s[s>s.mean()]
s[[4,3,1]]
data = [1,2,3]
df = pd.DataFrame(data)
df
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
df
d = {'one':pd.Series([1.,2.,3.],index=['a','b','c']),
    'two':pd.Series([1.,2.,3.,4.],index=['a','b','c','d'])}
pd.DataFrame(d)
pd.DataFrame(d,index=['d','b','a'])
pd.DataFrame(d,index=['d','b','a'],columns=['two','three'])
d = {'one':[1.,2.,3.,4.],
    'two':[4.,3.,2.,1.]}
pd.DataFrame(d)
pd.DataFrame(d,index=['a','b','c','d'])
data = [{'a':1,'b':2},{'a':5,'b':10,'c':20}]
pd.DataFrame(data)
pd.DataFrame(data,index=['frist','second'],columns=['a','b'])
d = {'one':pd.Series([1,2,3],index=['a','b','c']),
    'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df = pd.DataFrame(d)
df['three']=pd.Series([10,20,30],index=['a','b','c'])
df
df['four']=df['one']+df['three']
df
del df['one']
df
df.pop('two')
df
d = {'one':pd.Series([1,2],index=['a','b']),
    'two':pd.Series([1,2,3],index=['a','b','c'])}
df=pd.DataFrame(d)
print(df)
df.loc['b']
df.iloc[1]
df[2:4]


a    0
b    1
c    2
d    3
e    4
dtype: int64
   one  two
a  1.0    1
b  2.0    2
c  NaN    3


one  two
c  NaN    3

In [24]:
# 7-24 分别向dataframe中添加和删除一行元素
df2 = pd.DataFrame([[5,6],[7,8]],columns=['one','two'])
df = df.append(df2)
print(df)
df = df.drop(0)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  NaN    3
0  5.0    6
1  7.0    8
   one  two
a  1.0    1
b  2.0    2
c  NaN    3
1  7.0    8


C:\Users\lenovo\AppData\Local\Temp\ipykernel_48152\3738275888.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df2)


In [27]:
# 7-25 读取当前目录下的jivinfo.csv文件
data = pd.read_csv('job_info.csv',encoding='gbk')

In [33]:
# 7-26 将dataframe中的one列数据写入user.csv文件
d = {'one':pd.Series([1,2],index=['a','b']),
    'two':pd.Series([1,2,3],index=['a','b','c'])}
df=pd.DataFrame(d)
df.to_csv('user.csv',columns=['one'],index=True,header=True)

In [36]:
# 7-27 分别查看dataframe的前5行和后3行
arr = np.array([[19,58,25,77],[16,26,40,42],[63,11,2,87],
               [80,33,17,88],[63,36,6,20],[14,87,18,74]])
df = pd.DataFrame(arr,index=range(6),columns=list('ABCD'))
print(df.head())
print(df.tail(3))

    A   B   C   D
0  19  58  25  77
1  16  26  40  42
2  63  11   2  87
3  80  33  17  88
4  63  36   6  20
    A   B   C   D
3  80  33  17  88
4  63  36   6  20
5  14  87  18  74


In [37]:
# 7-28 将datafarame按列名降序排列
print(df.sort_index(axis=1,ascending=False))

    D   C   B   A
0  77  25  58  19
1  42  40  26  16
2  87   2  11  63
3  88  17  33  80
4  20   6  36  63
5  74  18  87  14


In [38]:
# 7-29 将dataframe先按第三行和B列进行升序排序，再同时按A列和B列进行降序排序
df.sort_values(by=2,axis=1)
df.sort_values(by='B')
df.sort_values(['A','B'],ascending=False)

A   B   C   D
3  80  33  17  88
4  63  36   6  20
2  63  11   2  87
0  19  58  25  77
1  16  26  40  42
5  14  87  18  74

In [40]:
# 7-30 将dataframe同时按key1列和key2列进行分组求均值
dict = {'key1':['a','b','a','b','a','b','a','a'],
       'key2':['one','one','two','three','two','two','one','three'],
       'data1':np.random.randint(1,8,8),
       'data2':np.random.randint(1,8,8)}
df = pd.DataFrame(dict)
print(df)
print(df.groupby(['key1','key2']).mean())
print(df.groupby(df.dtypes,axis=1).size())

  key1   key2  data1  data2
0    a    one      1      4
1    b    one      1      4
2    a    two      4      4
3    b  three      6      1
4    a    two      2      3
5    b    two      7      3
6    a    one      4      7
7    a  three      5      3
            data1  data2
key1 key2               
a    one      2.5    5.5
     three    5.0    3.0
     two      3.0    3.5
b    one      1.0    4.0
     three    6.0    1.0
     two      7.0    3.0
int32     2
object    2
dtype: int64


In [43]:
# 7-31 将dataframe按key1列分组求最小值、中间值和最大值
df.groupby('key1').aggregate(['min',np.median,max])
df.groupby('key1').aggregate({'data1':'min','data2':'max'})

C:\Users\lenovo\AppData\Local\Temp\ipykernel_48152\954711560.py:2: FutureWarning: ['key2'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.groupby('key1').aggregate(['min',np.median,max])


data1  data2
key1              
a         1      7
b         1      4

In [44]:
# 7-32 
df.groupby('key2').filter(lambda x:len(x)==2)

key1   key2  data1  data2
3    b  three      6      1
7    a  three      5      3

In [45]:
# 7-33 
df.groupby('key1').transform(np.mean)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_48152\4273624367.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('key1').transform(np.mean)


data1     data2
0  3.200000  4.200000
1  4.666667  2.666667
2  3.200000  4.200000
3  4.666667  2.666667
4  3.200000  4.200000
5  4.666667  2.666667
6  3.200000  4.200000
7  3.200000  4.200000

In [46]:
# 7-34
df.groupby('key1').min()
df.groupby('key1').mean()
df.groupby('key1').apply(lambda x:x.mean()+x.min())

C:\Users\lenovo\AppData\Local\Temp\ipykernel_48152\1005621703.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('key1').mean()
C:\Users\lenovo\AppData\Local\Temp\ipykernel_48152\1005621703.py:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.groupby('key1').apply(lambda x:x.mean()+x.min())
C:\Users\lenovo\AppData\Local\Temp\ipykernel_48152\1005621703.py:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only v

data1     data2  key1  key2
key1                                
a     4.200000  7.200000   NaN   NaN
b     5.666667  3.666667   NaN   NaN

In [47]:
# 7-35
df1 = df[3:5][['key1','data1']]
print(df1)

  key1  data1
3    b      6
4    a      2


In [48]:
# 7-36
import pandas as pd
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b),axis=0)
np.concatenate((a,b.T),axis=1)
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

In [49]:
# 7-37
import pandas as pd
ser1 = pd.Series(['A','B','C'],index=[1,2,3])
ser2 = pd.Series(['D','E','F'],index=[3,4,5])
pd.concat([ser1,ser2])
pd.concat([ser1,ser2],axis=1)

0    1
1    A  NaN
2    B  NaN
3    C    D
4  NaN    E
5  NaN    F

In [51]:
# 7-38
import pandas as pd
df1 = pd.DataFrame({'name':['Li','Han','Zhao','Su'],
                   'job':['Teacher','Worker','Doctor','Boss']})
df2 = pd.DataFrame({'name':['Li','Han','Pu','Chen'],
                    'date':[2004,2008,2012,2014]
                   })
print(df1)
print(df2)
df3 = pd.merge(df1,df2)
df3

   name      job
0    Li  Teacher
1   Han   Worker
2  Zhao   Doctor
3    Su     Boss
   name  date
0    Li  2004
1   Han  2008
2    Pu  2012
3  Chen  2014


name      job  date
0   Li  Teacher  2004
1  Han   Worker  2008

In [52]:
# 7-39
import pandas as pd
df = pd.DataFrame({'水果':['苹果','梨子','草莓'],'数量':[3,4,5],'价格':[4,5,6]})
print(df)
stack_df = df.stack()
print(stack_df)
type(stack_df)
print(stack_df.unstack())
type(stack_df.unstack())

   水果  数量  价格
0  苹果   3   4
1  梨子   4   5
2  草莓   5   6
0  水果    苹果
   数量     3
   价格     4
1  水果    梨子
   数量     4
   价格     5
2  水果    草莓
   数量     5
   价格     6
dtype: object
   水果 数量 价格
0  苹果  3  4
1  梨子  4  5
2  草莓  5  6


pandas.core.frame.DataFrame

In [58]:
# 7-40
import pandas as pd
import numpy as np
arr = np.array([[19,58,25,77,1],[16,26,40,42,np.NaN],[63,11,np.NaN,87,np.NaN],
               [80,33,17,np.NaN,np.NaN],[63,36,6,20,np.NaN],[14,87,18,74,65]])
df = pd.DataFrame(arr,index=range(6),columns=list('ABCDE'))
print(df)
df.isnull().sum()

      A     B     C     D     E
0  19.0  58.0  25.0  77.0   1.0
1  16.0  26.0  40.0  42.0   NaN
2  63.0  11.0   NaN  87.0   NaN
3  80.0  33.0  17.0   NaN   NaN
4  63.0  36.0   6.0  20.0   NaN
5  14.0  87.0  18.0  74.0  65.0


A    0
B    0
C    1
D    1
E    4
dtype: int64

In [59]:
# 7-41
df.drop(['C','D','E'],axis=1,inplace=True)
df

A     B
0  19.0  58.0
1  16.0  26.0
2  63.0  11.0
3  80.0  33.0
4  63.0  36.0
5  14.0  87.0

In [60]:
# 7-42
df.dropna(axis=0)
df.dropna(how='all')
df.dropna(axis=1)

A     B
0  19.0  58.0
1  16.0  26.0
2  63.0  11.0
3  80.0  33.0
4  63.0  36.0
5  14.0  87.0

In [63]:
# 7-43
df.fillna(value=5)
df.fillna(method='ffill')
df.fillna(method='bfill')
df.fillna(df.mean())

A     B
0  19.0  58.0
1  16.0  26.0
2  63.0  11.0
3  80.0  33.0
4  63.0  36.0
5  14.0  87.0

In [64]:
# 7-44
pd.isnull(df)

A      B
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False

In [65]:
# 7-45
df[np.abs(df.A-df.A.mean())>(3*df.A.std())]
df[np.abs(df.A-df.A.mean())<=(3*df.A.std())]

A     B
0  19.0  58.0
1  16.0  26.0
2  63.0  11.0
3  80.0  33.0
4  63.0  36.0
5  14.0  87.0

In [69]:
# 7-46
def filter_outlier(df,col_name):
    q1 = df[col_name].quantile(0.25)
    q3 = df[col_name].quantile(0.75)
    iqr = q3-q1
    fence_low = q1-1.5*iqr
    fence_high = q3+1.5*iqr
    df_out = df.loc[(df[col_name]>fence_low)&(df[col_name]<fence_high)]
    return df_out
filter_outlier(df,'A')

A     B
0  19.0  58.0
1  16.0  26.0
2  63.0  11.0
3  80.0  33.0
4  63.0  36.0
5  14.0  87.0

In [72]:
# 7-47
data = pd.DataFrame({'A':[1,1,2],'B':['b','a','b']})
data.duplicated('A')
data.drop_duplicates('A')
data.drop_duplicates('A',keep=False)


A  B
2  2  b

In [73]:
# 7-48
from datetime import datetime
date = datetime(year=2019,month=8,day=18)
date
date.strftime('%A')

'Sunday'

In [74]:
# 7-49
import numpy as np
date = np.array('2019-07-04',dtype=np.datetime64)
date

array('2019-07-04', dtype='datetime64[D]')

In [76]:
# 7-50
import pandas as pd
date = pd.to_datetime('4th of July,2019')
date
date.strftime('%A')
date+pd.to_timedelta(np.arange(3),'D')

DatetimeIndex(['2019-07-04', '2019-07-05', '2019-07-06'], dtype='datetime64[ns]', freq=None)

In [82]:
# 7-51
index = pd.DatetimeIndex(['2018-07-04','2018-08-04','2019-07-04'])
dates = pd.Series([0,1,2],index=index)
dates

2018-07-04    0
2018-08-04    1
2019-07-04    2
dtype: int64

In [84]:
# 7-52
dates.to_period('D')
dates-dates[0]
pd.date_range('2019-07-03','2019-07-07')
pd.date_range('2019-07-03',periods=5)

DatetimeIndex(['2019-07-03', '2019-07-04', '2019-07-05', '2019-07-06',
               '2019-07-07'],
              dtype='datetime64[ns]', freq='D')

In [86]:
# 7-53
str = 'hello world'
print(str.find('wo'))
print(str.find('we'))
print(str.split(' '))

6
-1
['hello', 'world']


In [87]:
# 7-54
name = pd.Series(['Li li','Han liang','Cheng ming','Liang jun'])
name.str.split('\s+')
name.str.extract('([LH])')

0
0    L
1    H
2  NaN
3    L

In [93]:
# 数据
index = pd.Index(data=['Lilei','Hanmei','Zhangsan','Lisi','Wangwu','Zhaoliu'],name='name')
data = {'age':[18,30,np.nan,40,np.nan,30],
       'city':['Bei Jing','Shang Hai','Guang Zhou','Shen Zhen',np.nan,''],
       'sex':[None,'male','female','male',np.nan,'unknow'],
       'birth':['2000-02-10','4th of July,1988',None,'08-07-1987',np.nan,'1988-10-17']}
user = pd.DataFrame(data=data,index=index)
user

age        city     sex             birth
name                                                
Lilei     18.0    Bei Jing    None        2000-02-10
Hanmei    30.0   Shang Hai    male  4th of July,1988
Zhangsan   NaN  Guang Zhou  female              None
Lisi      40.0   Shen Zhen    male        08-07-1987
Wangwu     NaN         NaN     NaN               NaN
Zhaoliu   30.0              unknow        1988-10-17

In [94]:
user['birth'] = pd.to_datetime(user.birth)
user

age        city     sex      birth
name                                         
Lilei     18.0    Bei Jing    None 2000-02-10
Hanmei    30.0   Shang Hai    male 1988-07-04
Zhangsan   NaN  Guang Zhou  female        NaT
Lisi      40.0   Shen Zhen    male 1987-08-07
Wangwu     NaN         NaN     NaN        NaT
Zhaoliu   30.0              unknow 1988-10-17

In [95]:
user.city.str.capitalize()

name
Lilei         Bei jing
Hanmei       Shang hai
Zhangsan    Guang zhou
Lisi         Shen zhen
Wangwu             NaN
Zhaoliu               
Name: city, dtype: object

In [96]:
user.city.str.len()

name
Lilei        8.0
Hanmei       9.0
Zhangsan    10.0
Lisi         9.0
Wangwu       NaN
Zhaoliu      0.0
Name: city, dtype: float64

In [97]:
user.city.str.replace('^S.*','')

C:\Users\lenovo\AppData\Local\Temp\ipykernel_48152\843699172.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  user.city.str.replace('^S.*','')


name
Lilei         Bei Jing
Hanmei                
Zhangsan    Guang Zhou
Lisi                  
Wangwu             NaN
Zhaoliu               
Name: city, dtype: object

In [98]:
user.city.str.split('')

name
Lilei             [, B, e, i,  , J, i, n, g, ]
Hanmei         [, S, h, a, n, g,  , H, a, i, ]
Zhangsan    [, G, u, a, n, g,  , Z, h, o, u, ]
Lisi           [, S, h, e, n,  , Z, h, e, n, ]
Wangwu                                     NaN
Zhaoliu                                   [, ]
Name: city, dtype: object

In [99]:
user.city.str.split('').str.get(1)

name
Lilei         B
Hanmei        S
Zhangsan      G
Lisi          S
Wangwu      NaN
Zhaoliu        
Name: city, dtype: object

In [102]:
user.city.str.split(' ',expand=True)

0     1
name                 
Lilei       Bei  Jing
Hanmei    Shang   Hai
Zhangsan  Guang  Zhou
Lisi       Shen  Zhen
Wangwu      NaN   NaN
Zhaoliu          None

In [103]:
user.city.str.extract('(\w+)\s+',expand=True)

0
name           
Lilei       Bei
Hanmei    Shang
Zhangsan  Guang
Lisi       Shen
Wangwu      NaN
Zhaoliu     NaN

In [106]:
user.city.str.extract('(\w+)\s+(\w+)',expand=True)

0     1
name                 
Lilei       Bei  Jing
Hanmei    Shang   Hai
Zhangsan  Guang  Zhou
Lisi       Shen  Zhen
Wangwu      NaN   NaN
Zhaoliu     NaN   NaN

In [107]:
user.city.str.extractall('(\w+)\s+')

0
name     match       
Lilei    0        Bei
Hanmei   0      Shang
Zhangsan 0      Guang
Lisi     0       Shen

In [108]:
user.city.str.contains('Zh')

name
Lilei       False
Hanmei      False
Zhangsan     True
Lisi         True
Wangwu        NaN
Zhaoliu     False
Name: city, dtype: object

In [109]:
user.city.str.get_dummies(sep=' ')

Bei  Guang  Hai  Jing  Shang  Shen  Zhen  Zhou
name                                                    
Lilei       1      0    0     1      0     0     0     0
Hanmei      0      0    1     0      1     0     0     0
Zhangsan    0      1    0     0      0     0     0     1
Lisi        0      0    0     0      0     1     1     0
Wangwu      0      0    0     0      0     0     0     0
Zhaoliu     0      0    0     0      0     0     0     0

In [111]:
csv_url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv'

df = pd.read_csv(csv_url)

In [112]:
df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('Studet_Alcohol.csv')

In [113]:
df.shape

(395, 33)

In [114]:
df.head(3)

school sex  age address famsize Pstatus  Medu  Fedu     Mjob     Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home  teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home    other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home    other  ...   

  famrel freetime  goout  Dalc  Walc health absences G1 G2  G3  
0      4        3      4     1     1      3        6  5  6   6  
1      5        3      3     1     1      3        4  5  5   6  
2      4        3      2     2     3      3       10  7  8  10  

[3 rows x 33 columns]

In [115]:
data = df.loc[:,'school':'guardian']
data.head(3)

school sex  age address famsize Pstatus  Medu  Fedu     Mjob     Fjob  \
0     GP   F   18       U     GT3       A     4     4  at_home  teacher   
1     GP   F   17       U     GT3       T     1     1  at_home    other   
2     GP   F   15       U     LE3       T     1     1  at_home    other   

   reason guardian  
0  course   mother  
1  course   father  
2   other   mother

In [116]:
data1 = df['guardian'].apply(lambda x:x.title())
data1.head(3)

0    Mother
1    Father
2    Mother
Name: guardian, dtype: object

In [117]:
df.Mjob.str.capitalize()
df.Fjob.str.capitalize()
df[['Mjob','Fjob']].head(3)

Mjob     Fjob
0  at_home  teacher
1  at_home    other
2  at_home    other

In [118]:
df['legal_drinker']=df['age']>17
df.head(3)

school sex  age address famsize Pstatus  Medu  Fedu     Mjob     Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home  teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home    other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home    other  ...   

  freetime goout  Dalc  Walc  health absences G1 G2  G3 legal_drinker  
0        3     4     1     1       3        6  5  6   6          True  
1        3     3     1     1       3        4  5  5   6         False  
2        3     2     2     3       3       10  7  8  10         False  

[3 rows x 34 columns]